// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: admission_control.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) The Libra Core Contributors
// SPDX-License-Identifier: Apache-2.0

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Additional statuses that are possible from admission control in addition
/// to VM statuses.
enum AdmissionControl_AdmissionControlStatusCode: SwiftProtobuf.Enum {
  typealias RawValue = Int

  /// Validator accepted the transaction.
  case accepted // = 0

  /// The sender is blacklisted.
  case blacklisted // = 1

  /// The transaction is rejected, e.g. due to incorrect signature.
  case rejected // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .accepted
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .accepted
    case 1: self = .blacklisted
    case 2: self = .rejected
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .accepted: return 0
    case .blacklisted: return 1
    case .rejected: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

/// -----------------------------------------------------------------------------
/// ---------------- Submit transaction
/// -----------------------------------------------------------------------------
/// The request for transaction submission.
struct AdmissionControl_SubmitTransactionRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Transaction signed by wallet.
  var signedTxn: Types_SignedTransaction {
    get {return _storage._signedTxn ?? Types_SignedTransaction()}
    set {_uniqueStorage()._signedTxn = newValue}
  }
  /// Returns true if `signedTxn` has been explicitly set.
  var hasSignedTxn: Bool {return _storage._signedTxn != nil}
  /// Clears the value of `signedTxn`. Subsequent reads from it will return its default value.
  mutating func clearSignedTxn() {_storage._signedTxn = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// AC response status containing code and optionally an error message.
struct AdmissionControl_AdmissionControlStatus {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var code: AdmissionControl_AdmissionControlStatusCode = .accepted

  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The response for transaction submission.
///
/// How does a client know if their transaction was included?
/// A response from the transaction submission only means that the transaction
/// was successfully added to mempool, but not that it is guaranteed to be
/// included in the chain.  Each transaction should include an expiration time in
/// the signed transaction.  Let's call this T0.  As a client, I submit my
/// transaction to a validator. I now need to poll for the transaction I
/// submitted.  I can use the query that takes my account and sequence number. If
/// I receive back that the transaction is completed, I will verify the proofs to
/// ensure that this is the transaction I expected.  If I receive a response that
/// my transaction is not yet completed, I must check the latest timestamp in the
/// ledgerInfo that I receive back from the query.  If this time is greater than
/// T0, I can be certain that my transaction will never be included.  If this
/// time is less than T0, I need to continue polling.
struct AdmissionControl_SubmitTransactionResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The status of a transaction submission can either be a VM status, or
  /// some other admission control/mempool specific status e.g. Blacklisted.
  var status: OneOf_Status? {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  var vmStatus: Types_VMStatus {
    get {
      if case .vmStatus(let v)? = _storage._status {return v}
      return Types_VMStatus()
    }
    set {_uniqueStorage()._status = .vmStatus(newValue)}
  }

  var acStatus: AdmissionControl_AdmissionControlStatus {
    get {
      if case .acStatus(let v)? = _storage._status {return v}
      return AdmissionControl_AdmissionControlStatus()
    }
    set {_uniqueStorage()._status = .acStatus(newValue)}
  }

  var mempoolStatus: Mempool_MempoolAddTransactionStatus {
    get {
      if case .mempoolStatus(let v)? = _storage._status {return v}
      return Mempool_MempoolAddTransactionStatus()
    }
    set {_uniqueStorage()._status = .mempoolStatus(newValue)}
  }

  /// Public key(id) of the validator that processed this transaction
  var validatorID: Data {
    get {return _storage._validatorID}
    set {_uniqueStorage()._validatorID = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The status of a transaction submission can either be a VM status, or
  /// some other admission control/mempool specific status e.g. Blacklisted.
  enum OneOf_Status: Equatable {
    case vmStatus(Types_VMStatus)
    case acStatus(AdmissionControl_AdmissionControlStatus)
    case mempoolStatus(Mempool_MempoolAddTransactionStatus)

    static func ==(lhs: AdmissionControl_SubmitTransactionResponse.OneOf_Status, rhs: AdmissionControl_SubmitTransactionResponse.OneOf_Status) -> Bool {
      switch (lhs, rhs) {
      case (.vmStatus(let l), .vmStatus(let r)): return l == r
      case (.acStatus(let l), .acStatus(let r)): return l == r
      case (.mempoolStatus(let l), .mempoolStatus(let r)): return l == r
      default: return false
      }
    }
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "admission_control"

extension AdmissionControl_AdmissionControlStatusCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Accepted"),
    1: .same(proto: "Blacklisted"),
    2: .same(proto: "Rejected"),
  ]
}

extension AdmissionControl_SubmitTransactionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubmitTransactionRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "signed_txn"),
  ]

  fileprivate class _StorageClass {
    var _signedTxn: Types_SignedTransaction? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _signedTxn = source._signedTxn
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._signedTxn)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._signedTxn {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: AdmissionControl_SubmitTransactionRequest) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._signedTxn != other_storage._signedTxn {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension AdmissionControl_AdmissionControlStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AdmissionControlStatus"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
    2: .same(proto: "message"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.code)
      case 2: try decoder.decodeSingularStringField(value: &self.message)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .accepted {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: AdmissionControl_AdmissionControlStatus) -> Bool {
    if self.code != other.code {return false}
    if self.message != other.message {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension AdmissionControl_SubmitTransactionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubmitTransactionResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "vm_status"),
    2: .standard(proto: "ac_status"),
    3: .standard(proto: "mempool_status"),
    4: .standard(proto: "validator_id"),
  ]

  fileprivate class _StorageClass {
    var _status: AdmissionControl_SubmitTransactionResponse.OneOf_Status?
    var _validatorID: Data = SwiftProtobuf.Internal.emptyData

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _status = source._status
      _validatorID = source._validatorID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1:
          var v: Types_VMStatus?
          if let current = _storage._status {
            try decoder.handleConflictingOneOf()
            if case .vmStatus(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._status = .vmStatus(v)}
        case 2:
          var v: AdmissionControl_AdmissionControlStatus?
          if let current = _storage._status {
            try decoder.handleConflictingOneOf()
            if case .acStatus(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._status = .acStatus(v)}
        case 3:
          var v: Mempool_MempoolAddTransactionStatus?
          if let current = _storage._status {
            try decoder.handleConflictingOneOf()
            if case .mempoolStatus(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._status = .mempoolStatus(v)}
        case 4: try decoder.decodeSingularBytesField(value: &_storage._validatorID)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      switch _storage._status {
      case .vmStatus(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      case .acStatus(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      case .mempoolStatus(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      case nil: break
      }
      if !_storage._validatorID.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._validatorID, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: AdmissionControl_SubmitTransactionResponse) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._status != other_storage._status {return false}
        if _storage._validatorID != other_storage._validatorID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
